global proc shelf_AdvancedSkeleton () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "AdvancedSkeleton" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "AdvancedSkeleton" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/AS.png" 
        -image1 "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/AS.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "source \"AdvancedSkeleton.mel\"; AdvancedSkeleton;" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Selector:biped" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Selector:biped" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/asBiped.png" 
        -image1 "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/asBiped.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "source \"AdvancedSkeletonFiles/Selector/biped.mel\";" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Selector:face" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Selector:face" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/asFace.png" 
        -image1 "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/icons/asFace.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "source \"AdvancedSkeletonFiles/Selector/face.mel\";" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "picker" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "picker" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/picker/pickerFiles/icons/picker.png" 
        -image1 "X:/id3a/pipeline/frontend-next/prod/plugins/advancedskeleton/6.6.71/scripts/AdvancedSkeletonFiles/picker/pickerFiles/icons/picker.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "source \"AdvancedSkeletonFiles/picker/picker.mel\";" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;

} 
